In [ ]:
1. Introduction to Lists

A list is a mutable (changeable), ordered sequence of elements.

Lists can hold items of any data type (including mixed types).

In [ ]:
list characterstics
ordered
items can be access
changable
heterogenous
can have duplicate value
are dynamic
can be nested
can contain any type of object

In [ ]:
#list v/s array
access
editing
deleting
operation
function

In [ ]:
comma seperated with in sq bracket
we can store multiple information under one variable

In [ ]:
#representation

In [33]:
# Example:
l1 = [1, "hello", 3.14, True]
l1

[1, 'hello', 3.14, True]

In [35]:
l=[20,"java",35.76,[30,40,24]]
l[3][1]

40

In [ ]:
#take every element as a row

In [36]:
import pandas as pd

In [3]:
l=['renu','ritu','sahil','yuvaan','advika']

df_col = pd.DataFrame(l,columns=['name'])
df_col

     name
0    renu
1    ritu
2   sahil
3  yuvaan
4  advika

In [4]:
data = [
    [10, 20, 30],   # Row 1
    [50, 60, 70],   # Row 2
    [90, 100, 120], # Row 3
    ['renu','ritu','yuvaan']
]

df1 = pd.DataFrame(data)
df1

      0     1       2
0    10    20      30
1    50    60      70
2    90   100     120
3  renu  ritu  yuvaan

In [9]:
data[2][1]

100

In [37]:
# Empty list
a = []
print(a)

[]

In [38]:
# With elements
b = [10, 20, 30]

In [41]:
# 2d list
d=[[1,2,3,4],[3,4],[3,45,34]]
d[2][0]

3

In [44]:
# type conversion
c = list("Python")  # ['P', 'y', 't', 'h', 'o', 'n']
c[5]

'n'

In [46]:
nums = [10, 20, 30, 40, 50]

# Positive indexing
nums[0]   # 10
nums[3]   # 40

40

In [47]:
# Negative indexing
nums[-1]  # 50
nums[-3]  # 30

30

In [58]:
d=[[1,2,3,4],[3,4],[3,45,34]]
d[1][1]

4

In [ ]:
sequence[start:stop:step]
start include
stop exclude

In [8]:
nums = [10, 20, 30, 40, 50, 60]

print(nums[1:4])    # [20, 30, 40]
print(nums[:3])     # [10, 20, 30]
print(nums[3:])     # [40, 50, 60]
print(nums[::2])    # [10, 30, 50]
print(nums[::-1])   # reverse: [60, 50, 40, 30, 20, 10]
print(nums[-3:]) #[40, 50, 60]
print(nums[-4:-1]) #[30, 40, 50]
print(nums[0:6:3])

[20, 30, 40]
[10, 20, 30]
[40, 50, 60]
[10, 30, 50]
[60, 50, 40, 30, 20, 10]
[40, 50, 60]
[30, 40, 50]
[10, 40]

In [67]:
nums = [1, 2, 3]

In [ ]:
# Change element
nums[1] = 200  # [1, 200, 3]

# Add new element
nums.append(4)  # [1, 200, 3, 4]

In [68]:
# Insert at specific position
nums.insert(1, [100,200])  # [1, 100, 200, 3, 4]

In [70]:
nums[1]

[100, 200]

In [ ]:
# Extend with (multiple items)
nums.extend([5, 6,8])  # [1, 100, 200, 3, 4, 5, 6,8]

In [ ]:
append
add a single element in the list
modfy the list itself
if y append element ,it will be  nested ,not merged
in dataframe -to add one or more row ,but now it is replce by concat

In [67]:
nums = [1, 2, 3]
nums.append(4) 
nums

[1, 2, 3, 4]

In [68]:
nums = [1, 2, 3]
nums.append([4,5,7]) #append a list as single element
nums

[1, 2, 3, [4, 5, 7]]

In [ ]:
#if y want to add multiple items individually use extend
# Extend with (multiple items)
nums.extend([5, 6,8])  # [1, 100, 200, 3, 4, 5, 6,8]

# editing

In [76]:
l=[2,4,6,7]

In [ ]:
l[0]=100
l

[100, 4, 6, 7]

In [55]:
l[0:2]=[100,200]
l

[100, 200, 6, 7]

In [66]:
l=[2,4,6,7]
l[1:2]=[200,300,400,400,500]    #1,2
print(l)     #[2, 200, [300, 400, 400], 500, 6, 7]
print(l[1])
print(l[5])

[2, 200, 300, 400, 400, 500, 6, 7]
200
500

In [12]:
l[-2:]=[5,6,7] #list can grow and shrink accordingly
l

[100, 200, 300, 5, 6, 7]

# deletion

In [ ]:
partially and fully

In [71]:
l

[2, 200, 300, 400, 400, 500, 6, 7]

In [72]:
del l[-1]
l

[2, 200, 300, 400, 400, 500, 6]

In [73]:
del l[1:3]
l

[2, 400, 400, 500, 6]

In [74]:
del l

In [75]:
l

NameError: name 'l' is not defined

In [79]:
nums = [1, 2, 3,3, 4, 5]

# Remove by value
nums.remove(3)  # [1, 2, 4, 5]

In [80]:
nums

[1, 2, 3, 4, 5]

In [ ]:
# Remove by index
nums.pop(2)     # removes 4 → [1, 2, 5]

# Remove last
nums.pop()      # removes 5 → [1, 2]

# Clear all elements
nums.clear()    # [] #empty list

# operation

In [ ]:
#operation
arithmetic  +
membership   in,not in
loop for

In [82]:
l1=[1,2,3]
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [ ]:
l3=l1+l2
l3

[1, 2, 3, 4, 5, 6]

In [81]:
l1=[1,2,3]
l1*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [85]:
l4=[i+j for i,j in zip(l1,l2)]
l4

[5, 7, 9]

In [4]:
s="renu"
s*3

'renurenurenu'

In [ ]:
# Concatenation
[1, 2] + [3, 4]  # [1, 2, 3, 4]

# Repetition
[0] * 4          # [0, 0, 0, 0]

In [16]:
# Membership
3 in [1, 2, 3]   # True

True

In [17]:
s="hello world"
'a' in s

False

In [30]:
nums = [10, 20, 30]

# Simple loop
for n in [10, 20, 30]:
    print(n)

10
20
30

In [97]:
a=list(enumerate([10,20,30]))
a

[(0, 10), (1, 20), (2, 30)]

In [18]:
for ind,val in enumerate([10,'ritu',20,30,'renu']):
    print(ind,val)

0 10
1 ritu
2 20
3 30
4 renu

# function

In [83]:
l=[[1,2,3,4,5],[2,3],[4,5,6,7]]
l[1]
len(l)

3

In [33]:
l=[[4,5,67],[2,3,4]]
len(l) #len() returns the number of elements in the outer list.
#min(l)

2

In [84]:
l=[4,5,67,2,3,4] 
len(l)

6

In [35]:
l=[4,5,67,2,3,4]   #1d
min(l)

2

In [86]:
l=[[4,5],[8,4]]  #compare with first element
max(l)

[8, 4]

In [90]:
l=[[14,5],[14,5,5]]
max(l)

[14, 5, 5]

In [91]:
l=[4,5,67,2,3,2,4]
l.count(2)

2

In [92]:
l=[[14,5,12],[4,6,5],[4,5,6]]
l.count([4,5,6]) #how many times x appears in the list

1

In [ ]:
list.index(x[, start[, end]])
Purpose: Returns the index of the first occurrence of x in the list.
value → The element you want to find
start (optional) → Search from this index
end (optional) → Search up to this index
Returns: The index of the first match
Raises: ValueError if the element is not found

In [93]:
l = [10, 20, 30, 20, 40,20]
l.index(20)

1

In [94]:
l.index(20)  # Output: 1, because the first 20 is at index 1
l.index(20, 2)  # Output: 3, start searching from index 2

3

In [29]:
#in 2d
#index() only matches entire elements, so it won’t find 5 inside [4,5,1]

l = [[4,5,1],[4,5]]
l.index([4,5,1])  # Output: 0
l.index([4,5])    # Output: 1

1

# reverse

In [95]:
l=[2,3,4,5,6]
l[::-1]

[6, 5, 4, 3, 2]

In [98]:
l

[6, 5, 4, 3, 2]

In [97]:
l.reverse()  # permanent update in original list
l

[6, 5, 4, 3, 2]

In [33]:
l[::-1]   # this is temporary

[2, 3, 4, 5, 6]

In [34]:
l

[6, 5, 4, 3, 2]

In [67]:
l1=[[1, 5, 4], [5, 4]]
l1.reverse()
l1

[[5, 4], [1, 5, 4]]

In [68]:
l=[[1, 5, 4], [5, 4]]
for i in l:        #[1,5,7]
    i.reverse()

print(l)

[[4, 5, 1], [4, 5]]

# permanent sort

In [ ]:
sort() sorts elements inside each sublist in ascending order by default.

In [35]:
l1=[10,4,2,3,6,78]
l1.sort()   # in ascending order(min at the top)
print(l1)

[2, 3, 4, 6, 10, 78]

In [36]:
l1

[2, 3, 4, 6, 10, 78]

In [75]:
l=[2,5,1]
l.sort()
print(l)

[1, 2, 5]

In [76]:
l

[1, 2, 5]

In [73]:
l1=[1,4,2,3,6,78]
l1.sort(reverse=True)  #3 sort in descending order (highest value on the top)
print(l1)

[78, 6, 4, 3, 2, 1]

In [77]:
l = [[4, 5, 1], [4, 5]]
for i in l:
    i.sort()
    print(i,end="")

[1, 4, 5][4, 5]

In [ ]:
sorted(iterable, key=None, reverse=False)   # temperory

In [ ]:
iterable can be-list,str,tuple,sets,dict,range

In [ ]:
non iterable-int,float

In [37]:
l = [5, 2, 9, 1]
new_list = sorted(l)
print(new_list)  # Output: [1, 2, 5, 9]
print(l)         # Original list remains: [5, 2, 9, 1]

[1, 2, 5, 9]
[5, 2, 9, 1]

In [80]:
l = [5, 2, 9, 1]
a=sorted(l)
print(l)
print(a)

[5, 2, 9, 1]
[1, 2, 5, 9]

In [ ]:
#copy
A shallow copy creates a new outer list object, 
but the elements themselves are references to the same objects in the original list.

In [ ]:


#Using copy module
import copy
copy3 = copy.copy(l)

In [100]:
suh=[1,2,3,4,5]   # l.copy()
aak=suh
print(id(suh))
print(id(aak))
suh[2]=20
print(suh)
print(aak)

3016974475136
3016974475136
[1, 2, 20, 4, 5]
[1, 2, 20, 4, 5]

In [99]:
#in 1d
l=[1,2,3,4,5]   # l.copy()
l1=l.copy()
print(id(l))
print(id(l1))
l[2]=20
print(l1)
print(l)

3016972076160
3016973892160
[1, 2, 3, 4, 5]
[1, 2, 20, 4, 5]

In [ ]:
#in case of 2d
it create a new outer list. But the inner lists are still the same objects:

In [104]:
l = [[1, 2], [3, 4]]
l1 = l.copy()
print(id(l1))
print(id(l))
print(l)
print(l1)
print(id(l1[1]))
print(id(l[1]))

3016979276288
3016972465856
[[1, 2], [3, 4]]
[[1, 2], [3, 4]]
3016974477056
3016974477056

In [44]:
print(id(l1[0]))
l1[0][0] = 100
print(l1)
print(l)
print(id(l1[1]))
print(id(l[1]))

2174881590656
[[100, 2], [3, 4]]
[[100, 2], [3, 4]]
2174881581632
2174881581632

In [ ]:
A deep copy create a duplicates copy of all nested objects, 
so changes in the original list do not affect the copy.

In [45]:
import copy
l = [[1, 2], [3, 4]]   # l.deepcopy()
l1= copy.deepcopy(l)
l1[0][0] = 500
print(l1) 
print(l)
print(id(l1[0]))
print(id(l[0]))

[[500, 2], [3, 4]]
[[1, 2], [3, 4]]
2174881431296
2174881430784

# deleting a range of element

In [3]:
a = [10, 20, 30, 40, 50]
for i in range(1, 4):   # indices 1, 2, 3
    a.pop(2)  # keep popping from index 1 each time
print(a)

[10, 20]

In [9]:
a = [10, 20, 30, 40, 50]
a.pop(1)
print(a)

[10, 30, 40, 50]

In [4]:
a = [10, 20, 30, 40, 50]
for val in [20, 30, 40]:
    a.remove(val)
print(a)

[10, 50]

In [10]:

a = [10, 20, 30, 40, 50, 60]
del a[1:4]  # removes elements at index 1, 2, 3
print(a)

[10, 50, 60]

In [38]:
items = ["apple", 10, "banana", 2]
print(sorted(items))

TypeError: '<' not supported between instances of 'int' and 'str'

In [46]:
#If you want to sort by string (alphabetical) order, convert all items to strings:
items = ["Apple", 10, "aanana", 2]
sorted_items = sorted(items, key=str)   # in ascending order
print(sorted_items) #"10" < "2" < "apple" < "banana" (lexicographically).

[10, 2, 'Apple', 'aanana']

In [ ]:
#Sort numerically where possible, then alphabetically

If you want numbers first (sorted numerically) and then strings (sorted alphabetically):

In [48]:
items = ["apple", 200, "banana", 20]

sorted_items = sorted(items, key=lambda x: (isinstance(x, str), str(x)))
print(sorted_items)

[20, 200, 'apple', 'banana']

In [51]:
items = [10, "2", "30"]
#print(sorted(items))  # ['10', '2', '30'] #That’s string order, not numeric order.

In [54]:
#To sort by number value:
print(sorted(items, key=int,reverse=False))  # ['2', '10', '30']

['2', 10, '30']

In [18]:
#count the no of character
s = "hello"
count = 0
for i in s:
    count += 1
print(count)   # Output: 5

5